-- liquibase formatted sql

-- changeset akimov:1
CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(50) NOT NULL
);

-- changeset akimov:2
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    issue_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_document_group FOREIGN KEY (group_id) REFERENCES groups(id)
);

-- changeset akimov:3
INSERT INTO groups (name, color) VALUES ('Общая группа', '#FFFFFF');