-- liquibase formatted sql

-- changeset akimov:1
CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(50) NOT NULL
);

-- changeset akimov:2
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    issue_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_document_group FOREIGN KEY (group_id) REFERENCES groups(id)
);

-- changeset akimov:3
INSERT INTO groups (name, color) VALUES ('Общая группа', '#FFFFFF');

-- changeset akimov:4
CREATE TABLE document_types(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    warning_days INT NOT NULL
);

-- changeset akimov:5
INSERT INTO document_types (name, warning_days) VALUES ('DOCUMENT', 14);
INSERT INTO document_types (name, warning_days) VALUES ('PASSPORT', 30);
INSERT INTO document_types (name, warning_days) VALUES ('CERTIFICATE', 14);
INSERT INTO document_types (name, warning_days) VALUES ('PASSWORD', 2);

-- changeset akimov:6
ALTER TABLE documents ADD COLUMN type_id BIGINT;

-- changeset akimov:7
UPDATE documents SET type_id = 1 WHERE type_id IS NULL;

-- changeset akimov:8
ALTER TABLE documents ALTER COLUMN type_id SET NOT NULL;
ALTER TABLE documents ADD CONSTRAINT fk_document_type FOREIGN KEY (type_id) REFERENCES document_types(id);

-- changeset akimov:9
ALTER TABLE documents DROP COLUMN type;

-- changeset akimov:10
ALTER TABLE document_types ADD COLUMN display_name VARCHAR(255);
UPDATE document_types SET display_name = name;
UPDATE document_types SET display_name = 'Документ' WHERE name = 'DOCUMENT';
UPDATE document_types SET display_name = 'Паспорт поверки прибора учета' WHERE name = 'PASSPORT';
UPDATE document_types SET display_name = 'Удостоверение' WHERE name = 'CERTIFICATE';
UPDATE document_types SET display_name = 'Пароль' WHERE name = 'PASSWORD';
ALTER TABLE document_types ALTER COLUMN display_name SET NOT NULL;